### ISSUE TITLE
Checklist for 9/23 edition:

### ISSUE THREAD

**Issue by machikoyasuda** [fullstackla/pairing-meetup#1]
## Organizers:
- @machikoyasuda
- @kitpearson
## Beforehand
- [x] Make Meetup invitation
- [x] Ask @learningnerd to cross-post to Learn to Code LA Meetup
- [x] Make nitpicks on members' latest submitted code
## Day of
- [x] Send e-mail. Add directions/parking information to invite.
- [x] Signs for the sidewalk/doors
- [ ] Nametags
- [x] Sign-in sheet
- [x] Snacks + Beverages
- [x] Projector set-up for live code refactoring
## Nice to have
- [ ] Make a USB stick of necessary code downloads: `Atom` code editor
- [x] Borrow / get old computer monitors, keyboards, mice
## Meetup member ideas:
- [x] @aquarchitect suggested we have a stopping point halfway through the night, and get volunteers to: present their code, break it down, and have someone else do a "nitpick" of it live. Could do a live refactoring session for 10-20 minutes. Any volunteers to have their code nitpicked/do a code review&refactoring live? Maybe @krainboltgreene?
